version: '1'
services:

  db:
    image: postgres:latest
    restart: always
    env_file: .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    image: flask:latest
    build: .
    env_file: .env
    volumes:
      - ./app:/code
    ports:
    - "5000:5000"
    depends_on:
    - db

volumes:
  postgres-data:
